### ISSUE TITLE
Can't download just one file from a generator

### ISSUE THREAD

**Issue by gheine** [apicollective/apibuilder-cli#21]
Currently it does not seem to be possible to download just a single file from a given generator. See e.g. https://app.apibuilder.io/apicollective/apibuilder-generator/0.12.58/http4s_0_15 
With the http4s generator I will always only need one of the generated files, never all. Sepcifying the following in the .apibuilder file gives the error below:

```
      generators:
        http4s_0_15: src/main/scala/generated/ApicollectiveApibuilderGeneratorV0ModelsJson.scala
```

```
Fetching code from https://api.apibuilder.io
  apicollective/apibuilder-generator/latest/http4s_0_15...
/Users/gheine/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:253:in `mkdir': File exists @ dir_s_mkdir - /Code/src/main/scala/generated/ApicollectiveApibuilderGeneratorV0ModelsJson.scala (Errno::EEXIST)
	from /Users/gheine/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:253:in `fu_mkdir'
	from /Users/gheine/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:227:in `block (2 levels) in mkdir_p'
	from /Users/gheine/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:225:in `reverse_each'
	from /Users/gheine/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:225:in `block in mkdir_p'
	from /Users/gheine/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:211:in `each'
	from /Users/gheine/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:211:in `mkdir_p'
	from /web/apidoc-cli/bin/apibuilder:371:in `block (4 levels) in <main>'
	from /web/apidoc-cli/bin/apibuilder:365:in `each'
	from /web/apidoc-cli/bin/apibuilder:365:in `block (3 levels) in <main>'
	from /web/apidoc-cli/bin/apibuilder:360:in `each'
	from /web/apidoc-cli/bin/apibuilder:360:in `block (2 levels) in <main>'
	from /web/apidoc-cli/bin/apibuilder:359:in `each'
	from /web/apidoc-cli/bin/apibuilder:359:in `block in <main>'
	from /web/apidoc-cli/bin/apibuilder:358:in `map'
	from /web/apidoc-cli/bin/apibuilder:358:in `<main>'
```

**Comment by mchimirev** [comment]
This used to work.  last parameter used to be filename, not directory.  

But I think previously downloading all files with a single command was not possible, we'd have to script a loop to download them, which was also not convenient in cases where you did want to download all files.  

For what it's worth, this is how I used to use cli script to get the client vs. how I use it now (from git change)

    -/web/apidoc-cli/bin/apidoc code gilt checkout-api ${version} play_2_4_client GiltCheckoutApiV0Client.scala > app/com/gilt/checkoutapi/models/package.scala
    +apibuilder code gilt checkout-api ${version} play_2_4_client .
    +mv ./com/gilt/checkout/api/v1/GiltCheckoutApiV1Client.scala app/com/gilt/checkoutapi/models/package.scala
